### ISSUE TITLE
Problem accessing Azure?

### ISSUE THREAD

**Issue by TonyFrend** [hassanhabib/anki_robot_with_azure#1]
Hi,

I am testing out your app and am having some issues.

I have a free Azure subscription to the Computer Vision Cognitive Service (see below).

**Resource group(change)
VectorVision
Status
Active
Location
UK South
Subscription(change)
Free Trial
Subscription ID
xxxxxx
API type
Computer Vision
Pricing tier
Free**

I have also entered my API key for the above service into the relevant (I think) line of your code (substituted for xxxxxxxxxx in the text below for security purposes) 

**params  = {'visualFeatures': 'Description', 'subscription-key': 'xxxxxxxxxx'}**

When I run the script I get the error message from Vector 'I didn't get that, try again'

I am probably making an obvious error.

Please advise.

Many thanks,

Tony

**Comment by hassanhabib** [comment]
@TonyFrend Did you make sure the url corresponds with your subscription? you might to change the url of the api, just the first part based on your location.
You wanna make sure the url as shown below:
![image](https://user-images.githubusercontent.com/1453985/50564346-fe464c80-0cd8-11e9-87ba-ed326f57c1a5.png)
matches the url you're calling with your subscription keys, so for the above example the api url would be something like this:
https://eastus2.api.cognitive.microsoft.com/vision/v2.0/analyze

Let me know if that works for ya :-)

**Comment by TonyFrend** [comment]
Hi,

You put your finger on my error. When I changed the URL to the endpoint URL for my service it worked as expected.

Many thanks for your prompt response.

Best regards and a Happy New Year,

Tony

**Comment by hassanhabib** [comment]
I will update my code with a comment so people would be aware when using it.
