### ISSUE TITLE
Enhancement request: Copy of what Vector has seen

### ISSUE THREAD

**Issue by TonyFrend** [hassanhabib/anki_robot_with_azure#2]
Not sure if this is possible but it would be great if your code could save a copy of what Vector has seen as a picture in a specified folder. 

The user could then review what Vector had seen and compare it to how Azure has interpreted the image.

Many thanks,

Tony

**Comment by hassanhabib** [comment]
If you remove this line https://github.com/hassanhabib/anki_robot_with_azure/blob/master/vector_loves_azure.py#L30 
from my code it will save the file on Vector's storage.

**Comment by TonyFrend** [comment]
Hi,

I tried commenting out that line and re-running the script.

I then went to the Vector App and looked at Vector's photos and could not see any relevant images.

Am I looking in the right place?

Many thanks,

Tony

**Comment by hassanhabib** [comment]
I would probably check Anki SDK website to find out where these files are saved and also modify line #19 to save it to that location.
